### ISSUE TITLE
Denote $ (USD) in Markdown $...$ delimited notation

### ISSUE THREAD

**Issue by 7k50** [cs150bf/ever-notedown#19]
Hi, it's me again :)

I am trying to create a simple table that contains mathematical notation including a dollar sign to denote US Dollars.

Since notation is demarcated by `$ notation $`, I have tried escaping the dollar sign, like so:

``` markdown
| Today     | 1 yr           |
|-----------|----------------|
| $ \$100 $ | $ \$100(1.1) $ |
```

Instead of getting the desired output:

| Today | 1 yr |
| --- | --- |
| $100 | $100(1.1) |

 I get this which seems to be a bug-erroneous output:

<img width="617" alt="screen shot 2015-11-02 at 20 11 10" src="https://cloud.githubusercontent.com/assets/14942350/10891965/393b4be0-81a1-11e5-8c89-6157c3f70748.png">

**Comment by cs150bf** [comment]
Thanks for finding the bug! Let me know if it's still an issue.

**Comment by 7k50** [comment]
I think it works as intended now. Thanks for fixing it!
