### ISSUE TITLE
Change color of body text in Preview Pane

### ISSUE THREAD

**Issue by 7k50** [cs150bf/ever-notedown#21]
Hi!

I'm looking for the code that regulates the color of body text in the Preview pane. Currently, the text is gray, but I would like it to be black – which is the color that Evernote uses to display the note after export.

I'm not sure if the Preview pane body text color is specific to Atom Editor or EVND, but I'm using "`Custom 1`" as my theme, in case this can be edited in the EVND theme css file.

Thanks for advising!

**Comment by cs150bf** [comment]
That's actually something that has been on my todo list for a while. I've pushed a quick fix that does what you want... there are more to be done properly from a developer's perspective (style encapsulation, shadow dom, etc.), but I probably won't be able to do it in near future, so hopefully that works for now.

**Comment by 7k50** [comment]
Thanks for addressing this – the Preview pane is definitely more legible now.

Great that you are considering advances in the future. I will close this issue for now :)
