### ISSUE TITLE
EVND broken after update to Atom Editor 1.2.0

### ISSUE THREAD

**Issue by 7k50** [cs150bf/ever-notedown#23]
`Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom`

I'm having this error since updating to Atom 1.2.0 yesterday. I'm assuming that this issue affects all users of EVND. But since I happened to do a clean reinstall of Homebrew/Git on my computer yesterday and this coincided with that, I thought it was best to post an issue to make sure the fault is not on my side.

Rebuilding the package in Atom does not work and gives a long traceback which could not be copied from the editor.

/W

**Comment by ZhiyuZhang** [comment]
Just started to use EVND, and I got the same issue when I update Atom to 1.2.0 today.

**Comment by rdhyee** [comment]
Same here.  The error looks a lot like what was reported in https://github.com/cs150bf/ever-notedown/issues/20.   The plugin worked in Atom 1.1 (as reported by others) and stopped working with the upgrade to 1.2.  I reinstalled Atom 1.1 in hopes of being able to stick with that version, but Atom auto-updated.  (I know of [no way to keep Atom from auto-updating](https://discuss.atom.io/t/is-there-an-easy-way-to-disable-atoms-auto-update-without-building-it-from-source/13346/22).)

Here's the error message I got when running `apm install ever-notedown` for Atom 1.2: https://gist.github.com/rdhyee/7a94d620e3be9ad2d87c.  (I'm running on OS X 10.9.5.  Any hope if I upgrade to a newer OS X version?)

**Comment by cs150bf** [comment]
Thanks for reporting the problem. I hope the new patch works for now, you probably need to do a few things after upgrading the package, though:
1. Close Atom
2. `$ cd ~/.atom/packages/ever-notedown`
3. `$ apm clean`
4. `$ apm install`
5. Restart Atom

**Comment by rdhyee** [comment]
@cs150bf EVND 0.2.14 is working for me so far.  I was able to hit the upgrade button in Packages panel. Thanks again for your awesome plugin (and your fix!)

**Comment by 7k50** [comment]
For some reason, `index.json` in my symlinked EVND Dropbox folder was nullified to zero bytes with the update (I think).

```
Uncaught TypeError: Cannot read property 'jsonOBJ' of null

/Users/winterflags/.atom/packages/ever-notedown/lib/note-manager-view.coffee:95
```

Luckily I had a backup of the contents and reinstated them. EVND now works. Thanks!

**Comment by cs150bf** [comment]
@winterflags That doesn't sound good... I cannot think of how updating the package would have any effect on the contents in the evnd folder, though. As a side note, you can use `git` to restore contents in the evnd folder to a previous timestamp, `index.json` and note files (markdown, enml, etc.) included.

I'll close this issue for now unless people are still experiencing this problem. Thanks guys for reporting!
