### ISSUE TITLE
Installing "ever-notedown@0.2.14" failed

### ISSUE THREAD

**Issue by 7k50** [cs150bf/ever-notedown#25]
I had to reinstall Atom due to problems with Atom's auto-update. As a part of this process, I deleted `~/Library/Application\ Support/com.github.atom.ShipIt` and `~/Library/Application\ Support/Atom`, updated Atom to 1.2.0 manually via direct DL from [atom.io](http://www.atom.io). EVND didn't work so I uninstalled it. Afterwards, `~/.atom/packages/ever-notedown` did not exist so I'm assuming that the uninstall was clean.

When trying to install the EVND package from "Install packages", I get this error:

```
Installing "ever-notedown@0.2.14" failed.

    ENOTEMPTY, rmdir '/Users/winterflags/.atom/packages/ever-notedown/lib'

Installing "ever-notedown@0.2.14" failed.

    events.js:72
        throw er; // Unhandled 'error' event

                  ^
Error: ENOENT, open '/Users/winterflags/.atom/packages/ever-notedown/node_modules/undersore-plus/LICENSE.md'
```

The EVND package is installed in "Packages", and the `ever-notedown` directory is `62 453 467 bytes (98,4 MB on disk) for 9 738 items` but trying to open the EVND Panel or Note list does nothing. Peculiarly, the following settings are present in "Package settings" but nothing else:
- Break On Single Newline
- Live Update
- Mathjax Custom Macros
- Open Note in Evernote Auto
- Syntax Theme
- Keybindings
- Readme

I'm not sure if it's related to EVND or to Atom itself, but I haven't had any problems with my other packages so far.

**Comment by 7k50** [comment]
Update: **Rebuilding packages succeded. Problem resolved.**

When opening Atom, clicking the "orange Bug icon" in the lower right corner produces this error:

```
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

ever-notedown 0.2.14

node.js:844
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Function.startup.resolveArgv0 (node.js:844:23)
    at startup (node.js:58:13)
    at node.js:935:3
```

Pressing "Rebuild packages" fixed the problem, restart of Atom was required.

**Comment by cs150bf** [comment]
I'm glad it now works for you. I'll close this issue for now.
