### ISSUE TITLE
Math flickers and disappears

### ISSUE THREAD

**Issue by egeerardyn** [cs150bf/ever-notedown#6]
When I try to typeset some math, the formulas only show briefly in the preview and then disappear.

![formulas-disappearing](https://cloud.githubusercontent.com/assets/177360/8472684/a6b163f8-20a3-11e5-9609-3b4e2a55aa29.gif)

Exporting this note to Evernote, doesn't display the formula either. I have also tried with other syntaxes for LaTeX formulas (`\[ ...\]`, `\begin{equation} ... \end{equation}` and `$ ... $`), all to no avail.

As you can see, I'm running OS X Yosemite (10.10.3), the latest version of Evernote at the time of writing (6.0.15) and the latest version of Atom (1.0.0).

**Comment by cs150bf** [comment]
@egeerardyn That's strange, the exact same formula works for me. 

![demo_issue_6](https://cloud.githubusercontent.com/assets/673917/8491174/2985864c-20ea-11e5-9afb-e610a36b18bd.gif)

To be honest I don't know where to start at this point... Would you mind checking a few things for me?
1. Is this problem unique to this particular equation? What if you add a second equation somewhere else in the same note?
2. Could you try creating a new note, with minimal content but a few math equations... Do they appear in preview?
3. Could you try starting Atom in dev mode (`atom -d` in command line, or "View -> Developer -> Open In Dev Mode"), open your note, right click on the region where the equation is supposed to be, and select "Inspect element"? Do you see HTML elements such as `<span class="math">`, `<div class="MathJax_SVG_Display">`? I suspect MathJax is not loaded properly for some reason...

![demo_issue_6_devmode](https://cloud.githubusercontent.com/assets/673917/8491361/e2749b06-20eb-11e5-8789-76c5f4bb2c7e.gif)

**Comment by egeerardyn** [comment]
I cannot reproduce this bug anymore: not using the same note, not with the same formula (or a different one), not in a new note.

So I think your suspicion might be right: MathJax might not have been loaded properly.
Thank you for the prompt response, though!
