### ISSUE TITLE
Possible to change the Font Size of MathJax renderings?

### ISSUE THREAD

**Issue by 7k50** [cs150bf/ever-notedown#63]
Is there a way to change the font size of MathJax renderings?

I had a look around in the config files, including the asset folder for MathJax, and tried a few things, but I couldn't get any font sizes to change.

Thank you!

**Comment by cs150bf** [comment]
This is late but I have just added [a line](https://github.com/cs150bf/ever-notedown/blob/a2709b15538091be82731a487bcd0d7817e84c95/lib/mathjax-helper.coffee#L192) in [version 0.2.27](https://github.com/cs150bf/ever-notedown/releases/tag/v0.2.27).

To change font size, open `ever-notedown/lib/mathjax-helper.coffee` and go to [line 192](https://github.com/cs150bf/ever-notedown/blob/a2709b15538091be82731a487bcd0d7817e84c95/lib/mathjax-helper.coffee#L192) (as of version 0.2.27), the default is `scale: 100`. Change the scaling factor (as a percentage) will change the mathjax output font size. 

See also: http://docs.mathjax.org/en/latest/options/SVG.html

I'll close this issue for now. Let me know if it doesn't work.
