### ISSUE TITLE
Can create a new note

### ISSUE THREAD

**Issue by bstsnail** [cs150bf/ever-notedown#65]
When click the Packages -> New Note -> Create New Note, there is nothing happen.

**Comment by cs150bf** [comment]
Sorry for the late (!) reply. Is this problem still occurring to you? If so, would you mind try starting Atom in debug mode (command line, `atom -d`), try creating a new note and then copy & paste what showed up in the debug panel to this thread? Thx!

**Comment by bstsnail** [comment]
Thanks, it's not happening now. I will open debug mode if it happen again.

**Comment by cs150bf** [comment]
That's good to hear! I'll close this issue for now. Feel free to reopen it if this problem reoccurs.
