### ISSUE TITLE
How to change font size?

### ISSUE THREAD

**Issue by 7k50** [cs150bf/ever-notedown#74]
Hey,

I had previously edited some setting for EVND whereby I had increased the font size of body text (for both the Preview pane, and what's rendered to Evernote).

Unfortunately after the last update, the setting seems to be gone, and now I can't remember how I did it. It wasn't that intuitive to me last time, because I had to spend quite some time to find the proper setting.

**Comment by 7k50** [comment]
Seems like the solution is to navigate to `/Users/niklas/.atom/packages/ever-notedown/assets` and find the CSS file for the theme you are using. Mine is called `custom1/style.css`. 

I then edited `font-size: 20px;` and other font-related things, saved and restarted Atom.

**Comment by cs150bf** [comment]
Just for reference, you can edit your custom theme by going (from the Atom menu bar) "Packages --> Ever Notedown --> Settings --> Themes (markdown -> HTML rendering)", then you can choose to edit `custom1/style.css` or `custom2/style.css`. You'll also need to make sure you choose either `Custom 1` or `Custom 2` from the package settings page ([demo here](https://www.evernote.com/shard/s68/sh/69fba11b-5562-4397-9647-cd6c21965fc0/c6b2e9105775dcde)). And yeah I'd recommend backing up the css file after you have modified it and got something you like.
